### ISSUE TITLE
Cannot login when installed with Mamba

### ISSUE THREAD

**Issue by victorlin** [nextstrain/cli#184] opened 2022-06-08 23:30 UTC
### Current Behavior

`nextstrain login` errors with an `ImportError` when passing a correct username/password.

```
% nextstrain login
Logging into Nextstrain.org…

Username: victorlin
Password: 

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/tmp/bin/nextstrain", line 10, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/tmp/lib/python3.10/site-packages/nextstrain/cli/__main__.py", line 10, in main
    return cli.run( argv[1:] )
  File "/opt/homebrew/Caskroom/miniconda/base/envs/tmp/lib/python3.10/site-packages/nextstrain/cli/__init__.py", line 33, in run
    return opts.__command__.run(opts)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/tmp/lib/python3.10/site-packages/nextstrain/cli/command/login.py", line 90, in run
    user = login(username, password)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/tmp/lib/python3.10/site-packages/nextstrain/cli/authn.py", line 54, in login
    session.authenticate(username, password)
  ...
  File "/opt/homebrew/Caskroom/miniconda/base/envs/tmp/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(/opt/homebrew/Caskroom/miniconda/base/envs/tmp/lib/python3.10/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so, 0x0002): Library not loaded: @rpath/libssl.1.1.dylib
  Referenced from: /opt/homebrew/Caskroom/miniconda/base/envs/tmp/lib/python3.10/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so
  Reason: tried: '/opt/homebrew/Caskroom/miniconda/base/envs/tmp/lib/libssl.1.1.dylib' (no such file), '/opt/homebrew/Caskroom/miniconda/base/envs/tmp/lib/libssl.1.1.dylib' (no such file), '/opt/homebrew/Caskroom/miniconda/base/envs/tmp/lib/python3.10/site-packages/cryptography/hazmat/bindings/../../../../../libssl.1.1.dylib' (no such file), '/opt/homebrew/Caskroom/miniconda/base/envs/tmp/lib/libssl.1.1.dylib' (no such file), '/opt/homebrew/Caskroom/miniconda/base/envs/tmp/lib/libssl.1.1.dylib' (no such file), '/opt/homebrew/Caskroom/miniconda/base/envs/tmp/lib/python3.10/site-packages/cryptography/hazmat/bindings/../../../../../libssl.1.1.dylib' (no such file), '/opt/homebrew/Caskroom/miniconda/base/envs/tmp/bin/../lib/libssl.1.1.dylib' (no such file), '/opt/homebrew/Caskroom/miniconda/base/envs/tmp/bin/../lib/libssl.1.1.dylib' (no such file), '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file)
```

### Expected behavior

Successful login.

```
% nextstrain login
Logging into Nextstrain.org…

Username: victorlin
Password: 

Credentials saved to /Users/vlin/.nextstrain/secrets.

Logged into nextstrain.org as victorlin.
Log out with `nextstrain logout`.
```

### How to reproduce
Steps to reproduce the current behavior:
1. `mamba create -n tmp -c conda-forge -c bioconda python=3.10 nextstrain-cli -y` (Reproduced with 3.8, 3.9, 3.10)
2. `conda activate tmp`
3. `nextstrain login`
4. Pass valid credentials
5. See error

### Your environment: if running Nextstrain locally

- Operating system: macOS 12.3.1
- Version: `nextstrain.cli 3.2.5`

### Additional context

- Pip install works fine.
- Tested with both `osx-arm64` and `osx-64` conda packages.

**Comment by tsibley** [comment] 2022-06-08 23:34
Hmm. Conda should be making the shared lib (`libssl.1.1.dylib`) available and it's not. This seems likely to be a Conda packaging error, possibly a mistake in the nextstrain-cli Bioconda recipe.

**Comment by tsibley** [comment] 2022-06-08 23:37
(Though seems like it could also easily be a packaging issue in our `cryptography` dep's Conda packaging.)

**Comment by tsibley** [comment] 2022-06-08 23:47
Unsurprisingly, I can't reproduce this on Linux, but I _am_ surprised to see that the Conda-packaged `cryptography` ends up resolving its `_openssl.abi3.so` binding of `libssl` to my system's copy instead of a copy within the Conda env.

```
$ ldd ~/.conda/envs/tmp/lib/python3.10/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so 
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fe0c0c6f000)
```

**Comment by tsibley** [comment] 2022-07-19 18:28
An equivalent issue locating the same OpenSSL shared library is affecting @corneliusroemer on Ubuntu 22.04, reported as https://github.com/nextstrain/cli/issues/203.

**Comment by tsibley** [comment] 2022-07-19 18:43
Reproduced this on Ubuntu 22.04 with a mix of @corneliusroemer's [recipe](https://github.com/nextstrain/cli/issues/203#issuecomment-1189418563) and @victorlin's above.

Setup on a fresh Ubuntu 22.04 VM:

```
mkdir -p ~/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
rm -rf ~/miniconda3/miniconda.sh
~/miniconda3/bin/conda init bash
exec bash
conda install mamba -n base -c conda-forge --yes
```

then pick up from step 1 onwards in issue description above.

**Comment by tsibley** [comment] 2022-07-19 18:46
Notably, Mamba installed OpenSSL 3.0.5 in step 1.

<details>

```
(base) ubuntu@tender-tiger:~$ mamba create -n tmp -c conda-forge -c bioconda python=3.8 nextstrain-cli -y

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.3) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['python=3.8', 'nextstrain-cli']

pkgs/main/linux-64       Using cache
pkgs/main/noarch         Using cache
pkgs/r/linux-64          Using cache
pkgs/r/noarch            Using cache
bioconda/noarch          [====================] (00m:00s) Done
bioconda/linux-64        [====================] (00m:01s) Done
conda-forge/noarch       [====================] (00m:02s) Done
conda-forge/linux-64     [====================] (00m:07s) Done
Transaction

  Prefix: /home/ubuntu/miniconda3/envs/tmp

  Updating specs:

   - python=3.8
   - nextstrain-cli


  Package                 Version  Build               Channel                     Size
─────────────────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex             0.1  conda_forge         conda-forge/linux-64        3 KB
  + _openmp_mutex             4.5  2_gnu               conda-forge/linux-64       23 KB
  + backrefs                  5.2  py38h578d9bd_1      conda-forge/linux-64      364 KB
  + boto3                 1.24.32  pyhd8ed1ab_0        conda-forge/noarch         72 KB
  + botocore              1.27.32  pyhd8ed1ab_0        conda-forge/noarch          6 MB
  + bracex                  2.2.1  pyhd8ed1ab_0        conda-forge/noarch         14 KB
  + brotlipy                0.7.0  py38h0a891b7_1004   conda-forge/linux-64      342 KB
  + bzip2                   1.0.8  h7f98852_4          conda-forge/linux-64      Cached
  + ca-certificates     2022.6.15  ha878542_0          conda-forge/linux-64      Cached
  + certifi             2022.6.15  py38h578d9bd_0      conda-forge/linux-64      155 KB
  + cffi                   1.15.1  py38h4a40e3a_0      conda-forge/linux-64      229 KB
  + charset-normalizer      2.1.0  pyhd8ed1ab_0        conda-forge/noarch         35 KB
  + cryptography           37.0.1  py38h9ce1e76_0      pkgs/main/linux-64          1 MB
  + docutils                 0.19  py38h578d9bd_0      conda-forge/linux-64      742 KB
  + fasteners              0.17.3  pyhd8ed1ab_0        conda-forge/noarch         20 KB
  + fsspec               2022.5.0  pyhd8ed1ab_0        conda-forge/noarch         96 KB
  + idna                      3.3  pyhd8ed1ab_0        conda-forge/noarch         55 KB
  + jmespath                1.0.1  pyhd8ed1ab_0        conda-forge/noarch         21 KB
  + ld_impl_linux-64       2.36.1  hea4e1c9_2          conda-forge/linux-64      667 KB
  + libffi                  3.4.2  h7f98852_5          conda-forge/linux-64       57 KB
  + libgcc-ng              12.1.0  h8d9b700_16         conda-forge/linux-64      940 KB
  + libgomp                12.1.0  h8d9b700_16         conda-forge/linux-64      459 KB
  + libnsl                  2.0.0  h7f98852_0          conda-forge/linux-64       31 KB
  + libuuid                2.32.1  h7f98852_1000       conda-forge/linux-64       28 KB
  + libzlib                1.2.12  h166bdaf_2          conda-forge/linux-64       63 KB
  + ncurses                   6.3  h27087fc_1          conda-forge/linux-64     1002 KB
  + nextstrain-cli          4.1.0  pyhdfd78af_0        bioconda/noarch            80 KB
  + openssl                 3.0.5  h166bdaf_0          conda-forge/linux-64        3 MB
  + pip                    22.1.2  pyhd8ed1ab_0        conda-forge/noarch          2 MB
  + pycparser                2.21  pyhd8ed1ab_0        conda-forge/noarch        100 KB
  + pyjwt                   2.4.0  pyhd8ed1ab_0        conda-forge/noarch         19 KB
  + pyopenssl              22.0.0  pyhd8ed1ab_0        conda-forge/noarch         49 KB
  + pysocks                 1.7.1  py38h578d9bd_5      conda-forge/linux-64       28 KB
  + python                 3.8.13  ha86cf86_0_cpython  conda-forge/linux-64       25 MB
  + python-dateutil         2.8.2  pyhd8ed1ab_0        conda-forge/noarch        240 KB
  + python_abi                3.8  2_cp38              conda-forge/linux-64        4 KB
  + readline                8.1.2  h0f457ee_0          conda-forge/linux-64      291 KB
  + requests               2.28.1  pyhd8ed1ab_0        conda-forge/noarch         53 KB
  + s3fs                    0.4.2  py_0                conda-forge/noarch         21 KB
  + s3transfer              0.6.0  pyhd8ed1ab_0        conda-forge/noarch         55 KB
  + setuptools             63.2.0  py38h578d9bd_0      conda-forge/linux-64        1 MB
  + six                    1.16.0  pyh6c4a22f_0        conda-forge/noarch         14 KB
  + sqlite                 3.39.1  h4ff8645_0          conda-forge/linux-64        2 MB
  + tk                     8.6.12  h27826a3_0          conda-forge/linux-64        3 MB
  + typing_extensions       4.3.0  pyha770c72_0        conda-forge/noarch         28 KB
  + urllib3               1.26.10  pyhd8ed1ab_0        conda-forge/noarch        101 KB
  + wcmatch                   8.3  pyhd8ed1ab_0        conda-forge/noarch         34 KB
  + wheel                  0.37.1  pyhd8ed1ab_0        conda-forge/noarch         31 KB
  + xz                      5.2.5  h516909a_1          conda-forge/linux-64      343 KB
  + zlib                   1.2.12  h166bdaf_2          conda-forge/linux-64       91 KB

  Summary:

  Install: 50 packages

  Total download: 49 MB

─────────────────────────────────────────────────────────────────────────────────────────

Finished _libgcc_mutex                        (00m:00s)               3 KB     28 KB/s
Finished _openmp_mutex                        (00m:00s)              23 KB    195 KB/s
Finished libgcc-ng                            (00m:00s)             940 KB      6 MB/s
Finished libgomp                              (00m:00s)             459 KB      3 MB/s
Finished libffi                               (00m:00s)              57 KB    380 KB/s
Finished ld_impl_linux-64                     (00m:00s)             667 KB      4 MB/s
Finished zlib                                 (00m:00s)              91 KB    588 KB/s
Finished wheel                                (00m:00s)              31 KB    177 KB/s
Finished idna                                 (00m:00s)              55 KB    305 KB/s
Finished six                                  (00m:00s)              14 KB     75 KB/s
Finished fsspec                               (00m:00s)              96 KB    425 KB/s
Finished cffi                                 (00m:00s)             229 KB   1008 KB/s
Finished python-dateutil                      (00m:00s)             240 KB      1 MB/s
Finished boto3                                (00m:00s)              72 KB    275 KB/s
Finished pyopenssl                            (00m:00s)              49 KB    182 KB/s
Finished libzlib                              (00m:00s)              63 KB    209 KB/s
Finished xz                                   (00m:00s)             343 KB      1 MB/s
Finished backrefs                             (00m:00s)             364 KB    896 KB/s
Finished jmespath                             (00m:00s)              21 KB     46 KB/s
Finished setuptools                           (00m:00s)               1 MB      3 MB/s
Finished pyjwt                                (00m:00s)              19 KB     40 KB/s
Finished pysocks                              (00m:00s)              28 KB     57 KB/s
Finished s3fs                                 (00m:00s)              21 KB     39 KB/s
Finished urllib3                              (00m:00s)             101 KB    191 KB/s
Finished tk                                   (00m:00s)               3 MB      7 MB/s
Finished brotlipy                             (00m:00s)             342 KB    665 KB/s
Finished botocore                             (00m:00s)               6 MB     11 MB/s
Finished bracex                               (00m:00s)              14 KB     24 KB/s
Finished readline                             (00m:00s)             291 KB    490 KB/s
Finished certifi                              (00m:00s)             155 KB    245 KB/s
Finished pip                                  (00m:00s)               2 MB      2 MB/s
Finished libuuid                              (00m:00s)              28 KB     42 KB/s
Finished charset-normalizer                   (00m:00s)              35 KB     49 KB/s
Finished sqlite                               (00m:00s)               2 MB      2 MB/s
Finished cryptography                         (00m:00s)               1 MB      2 MB/s
Finished s3transfer                           (00m:00s)              55 KB     72 KB/s
Finished openssl                              (00m:00s)               3 MB      4 MB/s
Finished typing_extensions                    (00m:00s)              28 KB     36 KB/s
Finished requests                             (00m:00s)              53 KB     66 KB/s
Finished libnsl                               (00m:00s)              31 KB     36 KB/s
Finished pycparser                            (00m:00s)             100 KB    121 KB/s
Finished fasteners                            (00m:00s)              20 KB     23 KB/s
Finished python_abi                           (00m:00s)               4 KB      5 KB/s
Finished wcmatch                              (00m:00s)              34 KB     38 KB/s
Finished docutils                             (00m:00s)             742 KB    819 KB/s
Finished ncurses                              (00m:00s)            1002 KB      1 MB/s
Finished nextstrain-cli                       (00m:00s)              80 KB     84 KB/s
Finished python                               (00m:00s)              25 MB     26 MB/s
Downloading  [========================================================] (00m:08s)   51.36 MB/s
Extracting   [========================================================] (00m:08s)      48 / 48
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate tmp
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

</details>

This means that only `libssl.so` and `libssl.so.3` are installed in the env:

```
(tmp) ubuntu@tender-tiger:~$ find miniconda3/envs/tmp/ -iname '*libssl*'
miniconda3/envs/tmp/lib/pkgconfig/libssl.pc
miniconda3/envs/tmp/lib/libssl.so
miniconda3/envs/tmp/lib/libssl.so.3
```

which is obviously incompatible with `cryptography` looking for OpenSSL 1.1 via `libssl.so.1.1`:

```
  File "/home/ubuntu/miniconda3/envs/tmp/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
```

So there is some packaging or dep resolution error here.

**Comment by tsibley** [comment] 2022-07-19 18:49
Also notably, Conda's `base` env has OpenSSL 1.1.

<details>

```
(tmp) ubuntu@tender-tiger:~$ find miniconda3/ -iname '*libssl*'
miniconda3/envs/tmp/lib/pkgconfig/libssl.pc
miniconda3/envs/tmp/lib/libssl.so
miniconda3/envs/tmp/lib/libssl.so.3
miniconda3/lib/libssl.a
miniconda3/lib/libssl.so.1.1
miniconda3/lib/pkgconfig/libssl.pc
miniconda3/lib/libssl.so
miniconda3/pkgs/openssl-1.1.1n-h7f8727e_0/lib/libssl.a
miniconda3/pkgs/openssl-1.1.1n-h7f8727e_0/lib/libssl.so.1.1
miniconda3/pkgs/openssl-1.1.1n-h7f8727e_0/lib/pkgconfig/libssl.pc
miniconda3/pkgs/openssl-1.1.1n-h7f8727e_0/lib/libssl.so
miniconda3/pkgs/openssl-1.1.1q-h7f8727e_0/lib/libssl.a
miniconda3/pkgs/openssl-1.1.1q-h7f8727e_0/lib/libssl.so.1.1
miniconda3/pkgs/openssl-1.1.1q-h7f8727e_0/lib/pkgconfig/libssl.pc
miniconda3/pkgs/openssl-1.1.1q-h7f8727e_0/lib/libssl.so
miniconda3/pkgs/openssl-3.0.5-h166bdaf_0/lib/pkgconfig/libssl.pc
miniconda3/pkgs/openssl-3.0.5-h166bdaf_0/lib/libssl.so
miniconda3/pkgs/openssl-3.0.5-h166bdaf_0/lib/libssl.so.3
```

</details>

**Comment by tsibley** [comment] 2022-07-19 19:02
Can't reproduce on Ubuntu 20.04… but only because the base OS OpenSSL is 1.1 and found by `cryptography`. OpenSSL 3 is still what's installed into the env by Mamba!

```
  + openssl                 3.0.5  h166bdaf_0          conda-forge/linux-64        3 MB
```

```
(tmp) ubuntu@soothing-lamprey:~$ find miniconda3/envs/tmp/ -iname '*libssl*'
miniconda3/envs/tmp/lib/pkgconfig/libssl.pc
miniconda3/envs/tmp/lib/libssl.so
miniconda3/envs/tmp/lib/libssl.so.3

(tmp) ubuntu@soothing-lamprey:~$ ldd miniconda3/envs/tmp/lib/python3.8/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so | grep ssl
	libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f4dc8868000)

(tmp) ubuntu@soothing-lamprey:~$ apt policy openssl
openssl:
  Installed: 1.1.1f-1ubuntu2.16
  Candidate: 1.1.1f-1ubuntu2.16
  Version table:
 *** 1.1.1f-1ubuntu2.16 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.1f-1ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

**Comment by tsibley** [comment] 2022-07-19 19:04
This explains why [I was surprised a month ago](https://github.com/nextstrain/cli/issues/184#issuecomment-1150522832).

**Comment by tsibley** [comment] 2022-07-19 20:57
I isolated the issue further to some interplay between the `python` and `cryptography` Conda packages _and_ Mamba's environment resolution. Conda's environment resolution does not exhibit the same issue!

I ran the following sets of commands:

```
conda create -n tmp -c conda-forge -c bioconda cryptography <<<no
conda create -n tmp -c conda-forge -c bioconda python cryptography <<<no

mamba create -n tmp -c conda-forge -c bioconda cryptography <<<no
mamba create -n tmp -c conda-forge -c bioconda python cryptography <<<no
```

Conda consistently resolved OpenSSL 1.1.1 while Mamba resolved OpenSSL 3.0.5 when `python` was included explicitly.

The full output from each command:

- [conda-without-python.txt](https://github.com/nextstrain/cli/files/9144676/conda-without-python.txt)
- [conda-with-python.txt](https://github.com/nextstrain/cli/files/9144677/conda-with-python.txt)
- [mamba-without-python.txt](https://github.com/nextstrain/cli/files/9144678/mamba-without-python.txt)
- [mamba-with-python.txt](https://github.com/nextstrain/cli/files/9144679/mamba-with-python.txt)

Note the differences in output (i.e. environment resolution) between the pair of Mamba runs:

```diff
diff --git a/mamba-without-python.txt b/mamba-with-python.txt
index 5274da9..5bc0f39 100644
--- a/mamba-without-python.txt
+++ b/mamba-with-python.txt
@@ -12,6 +12,7 @@ Transaction
 
   Updating specs:
 
+   - python
    - cryptography
 
 
@@ -25,7 +26,7 @@ Transaction
   + bzip2                 1.0.8  h7f98852_4          conda-forge/linux-64     Cached
   + ca-certificates   2022.6.15  ha878542_0          conda-forge/linux-64     Cached
   + cffi                 1.15.1  py310h255011f_0     conda-forge/linux-64     231 KB
-  + cryptography         37.0.4  py310h597c629_0     conda-forge/linux-64       2 MB
+  + cryptography         37.0.1  py310h9ce1e76_0     pkgs/main/linux-64         2 MB
   + ld_impl_linux-64     2.36.1  hea4e1c9_2          conda-forge/linux-64     Cached
   + libffi                3.4.2  h7f98852_5          conda-forge/linux-64     Cached
   + libgcc-ng            12.1.0  h8d9b700_16         conda-forge/linux-64     Cached
@@ -34,10 +35,10 @@ Transaction
   + libuuid              2.32.1  h7f98852_1000       conda-forge/linux-64     Cached
   + libzlib              1.2.12  h166bdaf_2          conda-forge/linux-64     Cached
   + ncurses                 6.3  h27087fc_1          conda-forge/linux-64     Cached
-  + openssl              1.1.1q  h166bdaf_0          conda-forge/linux-64       2 MB
+  + openssl               3.0.5  h166bdaf_0          conda-forge/linux-64       2 MB
   + pip                  22.1.2  pyhd8ed1ab_0        conda-forge/noarch       Cached
   + pycparser              2.21  pyhd8ed1ab_0        conda-forge/noarch       Cached
-  + python               3.10.5  h582c2e5_0_cpython  conda-forge/linux-64      29 MB
+  + python               3.10.5  ha86cf86_0_cpython  conda-forge/linux-64      29 MB
   + python_abi             3.10  2_cp310             conda-forge/linux-64       4 KB
   + readline              8.1.2  h0f457ee_0          conda-forge/linux-64     Cached
   + setuptools           63.2.0  py310hff52083_0     conda-forge/linux-64       1 MB
@@ -81,5 +82,5 @@ Confirm changes: [Y/n] Aborted.
 █████████████████████████████████████████████████████████████
 
 
-Looking for: ['cryptography']
+Looking for: ['python', 'cryptography']

```

vs. the pair of Conda runs:

```diff
--- a/conda-without-python.txt
+++ b/conda-with-python.txt
@@ -18,6 +18,7 @@ Please update conda by running
 
   added / updated specs:
     - cryptography
+    - python
 
 
 The following packages will be downloaded:
```

Mamba resolves the same version (3.10.5) but _a different build_ (`h582c2e5_0_cpython` vs. `ha86cf86_0_cpython`). It also resolves a _different version_ (37.0.4 vs. 37.0.1) of `cryptography` from a _different channel_ (conda-forge vs. pkgs/main).

This seems very much like a Mamba bug or a `cryptography` packaging bug or both.

**Comment by tsibley** [comment] 2022-07-19 21:04
@corneliusroemer Besides the potential workaround above of omitting `python` from your environment spec, if you're using our Docker runtime on your AWS VM, you can avoid Conda/Mamba entirely and instead install Nextstrain CLI from:

1. Pip, or
2. The new standalone installation archive (not yet officially advertised), e.g. https://github.com/nextstrain/cli/releases/download/4.1.1/nextstrain-cli-4.1.1-standalone-x86_64-unknown-linux-gnu.tar.gz

**Comment by tsibley** [comment] 2022-07-19 21:09
Notably, if I don't use the conda-forge channel, then OpenSSL is resolved correctly to 1.1.1. The issue seems to arise from Mamba resolving cryptography (and only that) from pkgs/main instead of conda-forge. Conda always resolves everything from conda-forge.

**Comment by tsibley** [comment] 2022-07-19 21:46
A similar resolution discrepancy arising in [this Mamba issue](https://github.com/mamba-org/mamba/issues/1581), which mentions an "OpenSSL migration" that may be at fault here.

It seems like not using `--strict-channel-priority` is biting us here; it's [recommended by conda-forge](https://conda-forge.org/docs/user/tipsandtricks.html#using-multiple-channels). If I use it, all is well with Mamba. AIUI, with relaxed channel priorities (the default) the resolver is allowed to pull packages from lower priority channels to solve conflicts instead of using backtracking (?) to solve conflicts using higher priority channels.

**Comment by corneliusroemer** [comment] 2022-07-19 21:49
Very nice investigation, a pleasure to follow.

I presume you will raise this with the relevant folks at mamba and/or the conda-forge feedstock so that this gets solved?

Great to know some workarounds - there're a few reasons why I can't use the stock docker image (yet as is).

I'll learn more docker so I can add whatever I need.

I guess one very big advantage of me using the image more is that it'll cause improvements in the image which will benefit many.

Though test driving mamba is also not useless since this is how a significant share of users do things.

**Comment by corneliusroemer** [comment] 2022-07-19 22:21
Ok, so I did a quick internet search and found things that should help us figure out a workaround (we should fix the `install nextstrain via mamba` docs)

Relevant:
https://github.com/conda-forge/conda-forge.github.io/issues/1528
https://github.com/conda-forge/cryptography-feedstock/pull/80

There seems to have been an issue with openssl3 but it looks like it has bene fixed with v37 of cryptography. Maybe the wrong version is pinned by a dependency of nextstrain-cli?
https://github.com/conda-forge/cryptography-feedstock/pull/97

Maybe we're using too old a version of Python?

Possible workaround: 
- pinning openssl: https://github.com/conda/conda/issues/11111#issuecomment-1029211727 
- or using strict channel priority in our recipe: https://github.com/conda-forge/conda-forge.github.io/issues/434

This could maybe help in the future: https://github.com/conda-forge/cryptography-feedstock/pull/98

It could be as simple as adding flags `--strict-channel-priority` and `--override-channels` when installing the environment.

```
conda install -c conda-forge --strict-channel-priority --override-channels
```

**Comment by tsibley** [comment] 2022-07-19 22:44
> I presume you will raise this with the relevant folks at mamba and/or the conda-forge feedstock so that this gets solved?

I believe the issue is in our install instructions/usage of conda-forge, not an upstream issue. Specifically, I think we need to update our docs to use `--strict-channel-priority` (see also below). I have a proposed change locally that I need to make into a PR for docs.nextstrain.org.

> Could be possible to just delete main from the channels then. Probably a good idea anyways. I think this may even be what mamba folks will say. "Not a bug, you shouldn't use main" but let's see...

My understanding is that "don't use the default channel when using conda-forge/bioconda" was the recommendation in the past, but that nowadays the default should be included as lowest priority and strict priorities should be used. This is noted in [the docs I'd linked to previously](https://conda-forge.org/docs/user/tipsandtricks.html#using-multiple-channels):

![image](https://user-images.githubusercontent.com/79913/179859777-85bcfc7f-7f20-4c55-bfee-a71c70853f03.png)

> Maybe the wrong version is pinned by a dependency of nextstrain-cli?

I don't think so, as I expect that would manifest as all invocations I tried above failing.

> Maybe we're using too old a version of Python?

No, this happens across Python versions. (I tried it earlier but didn't report that.)

> https://github.com/conda-forge/cryptography-feedstock/pull/98
> 
> It could be as simple as adding flags `--strict-channel-priority` and `--override-channels` when installing the environment.
> 
> ```
> conda install -c conda-forge --strict-channel-priority --override-channels
> ```

Yes and no. I think it's a matter of adding `--strict-channel-priority` alone (and maybe being explicit about priority of `-c defaults`?). We don't want `--override-channels`, I think, as that removes the default channel, which we want to keep (see above).

> How is the standalone different from current packaging? Does it not use any openssl deps? So we could just do binary repackaging in bioconda as opposed to making it a python package?

It's a ~fully self-contained installation archive (incl. Python) that can be downloaded, extracted, and run directly without any bootstrapping on Linux, macOS, and Windows. OpenSSL is included. There's [more in the changelog](https://github.com/nextstrain/cli/blob/72500a88b2311a48023907bd311711d9e9367eee/CHANGES.md#development-1) (search for "standalone").

We could do binary repackaging in Bioconda, but that goes pretty directly against the policy of Bioconda (and somewhat defeats the point of Conda).

**Comment by corneliusroemer** [comment] 2022-07-19 23:08
I arrived independently at the same conclusion and have also tested the resolution via mamba (at least on mac).

Agree with you, we should just add `--strict-channel-priority`.

To make updating seemless, not needing to remember all these flags, I recommend to run the following commands to set environment `.condarc`:

```bash
conda config --env --set channel_priority strict
conda config --env --add channels conda-forge
conda config --env --add channels bioconda
```

Bioconda is actually ok with binary repackaging - conda-forge is quite against it.

Yes, it maybe somewhat defeats the point, but in the end conda has become **the** cross-platform package manager for python & beyond so it's useful to have everything in there, even binaries. Then you don't need to say: "for Ubuntu use `sudo apt get libssl` for mac, install homebrew etc. etc."

**Comment by tsibley** [comment] 2022-07-19 23:47
See https://github.com/nextstrain/docs.nextstrain.org/pull/120.

**Comment by tsibley** [comment] 2022-08-25 21:34
Resolved by the documentation change above.

**Closed by tsibley** 2022-08-25 21:34 UTC
Labels: bug
