### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### ISSUE THREAD

**Issue by victorlin** [nextstrain/cli#171] opened 2022-04-26 23:21 UTC
### Current Behavior

[See recent GitHub Actions workflow failures on nextstrain.org](https://github.com/nextstrain/nextstrain.org/actions/workflows/update-dataset-listings.yml?query=is%3Afailure) since [the release of `cryptogrphy=37.0.0`](https://pypi.org/project/cryptography/37.0.0/#history).

Error is from `nextstrain remote upload` command:

```
Original exception was:
Traceback (most recent call last):
  File "/home/runner/.local/bin/nextstrain", line 5, in <module>
    from nextstrain.cli.__main__ import main
  File "/home/runner/.local/lib/python3.8/site-packages/nextstrain/cli/__init__.py", line 17, in <module>
    from .argparse    import HelpFormatter, register_commands, register_default_command
  File "/home/runner/.local/lib/python3.8/site-packages/nextstrain/cli/argparse.py", line 9, in <module>
    from .util import format_usage
  File "/home/runner/.local/lib/python3.8/site-packages/nextstrain/cli/util.py", line 3, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

### Expected behavior

No error.

### How to reproduce

Re-run the workflow?

### Possible solution

- Downgrade whatever uses `cryptography` in the dependency chain, or wait for a fix.

### Additional context

- https://github.com/pyca/pyopenssl/issues/1114
- https://github.com/pyca/cryptography/issues/7126

**Comment by tsibley** [comment] 2022-04-27 17:57
## Reproduction

The error arises from combining an old version of `pyopenssl` (at least as old as `20.0.1`) with a new version of `cryptography` (>= `37.0.0`).  `pyopenssl` depends on `cryptography`.

With those distributions installed, I was able to reproduce via several means (using Python 3.8.10, FWIW).  Contrived example:

    python3 -c 'from OpenSSL import crypto'

In the real world though this occurs after a chain of imports kicked off by `nextstrain-cli` importing `requests`:

    python3 -c 'import requests'

which I could only get to trigger the error if `requests` was also sufficiently old (at least `2.22.0`).

Any of these alone fix the issue for me once I've reproduced it locally:

  - Uninstall `pyopenssl`.
  
    It's not strictly necessary and isn't automatically installed on a fresh
    venv.  **The GitHub Actions environment has it installed by default,
    however.**

  - Upgrade `requests` to `2.27.1` (a version or two earlier may also be sufficient; didn't test).

  - Upgrade `pyopenssl` to `22.0.0` (a version or two earlier may also be sufficient; didn't test).

  - Downgrade `cryptography` to `<37.0.0`.

Notably, this issue arises in GitHub Actions specifically because its default Python 3.8.10 in the Ubuntu 20.04 image has both `requests` and `pyopenssl` pre-installed with old versions, and so they're not upgraded during `nextstrain-cli` install time (in `ncov-ingest`'s `./bin/setup-github-workflow` for example).

  - requests is 2.22.0
  - pyopenssl is 20.0.1 (or another problematic version)

Neither of these old libraries are present in a fresh venv created from a standard Python base install (i.e. without `requests` installed into the Python's `dist-packages`).  Full reproduction:

    tmp=$(mktemp -d)
    python3 -m venv $tmp
    source $tmp/bin/activate
    python3 -m pip install --upgrade pip setuptools wheel
    python3 -m pip install pyopenssl==20.0.1 requests==2.22.0
    python3 -m pip install nextstrain-cli
    python3 -c 'import requests'


## Resolution

As a short-term patch, we can start upgrading `pyopenssl` and/or `requests` in our CI workflows on GitHub Actions (e.g. in `ncov-ingest`'s `bin/setup-github-workflow`).  This is simple to do, easy to reason about, and has a limited scope of impact (i.e. doesn't involve publishing a new version of `nextstrain-cli`, which could accidentally introduce other installation
issues).

We could stop there and wait to implement any other fix in `nextstrain-cli` itself until and if the problem becomes more common.  So far, we've only seen it on our own GitHub Actions CI due to the pre-installed older versions of libs.

The best (but unattainable) long-term fix would be for `cryptography`'s distribution metadata to start declaring a conflict with older `pyopenssl` versions, but alas Python's [distribution metadata spec](https://packaging.python.org/en/latest/specifications/core-metadata/) doesn't include such a field (unlike many other software packaging systems).

The best _attainable_ long-term fix, if we choose to make any, is probably to bump up our minimum dep on `requests`.  This fixes the issue when an old version of `pyopenssl` is independently installed.  Since we don't require `pyopenssl` ourselves, we can't place a minimum version dep on it without causing it to be installed.  Placing a maximum version dep on `cryptography` is a non-starter, since we want bug fixes and improvements to that security-related code.

**Comment by tsibley** [comment] 2022-04-27 18:31
We've seen this error now in our GitHub Actions workflows for:

- [ ] [nextstrain/nextstrain.org](https://github.com/nextstrain/nextstrain.org) ([example](https://github.com/nextstrain/nextstrain.org/runs/6198765539?check_suite_focus=true))
- [ ] [nextstrain/ncov-ingest](https://github.com/nextstrain/ncov-ingest) ([example](https://github.com/nextstrain/ncov-ingest/runs/6198875772?check_suite_focus=true))

Notably we don't see it for this repo's (Nextstrain CLI's) workflows because (due to https://github.com/nextstrain/cli/pull/160) they `pip install` Nextstrain CLI into a Conda env in which the following are already installed (pulled in by a prior `mamba install augur auspice snakemake`):

- pyopenssl 22.0.0 (👍 new enough)
- cryptography 36.0.0 (👍 old enough)
- requests 2.27.1 (👍 new enough)

These are all Conda packagings of the PyPI distributions.  Conda doesn't yet have `cryptography` `37.0.0`, but even if it did the other versions are still new enough.

Also notably we don't see the error for [nextstrain/ncov](https://github.com/nextstrain/ncov)'s GitHub Actions workflows because it uses `actions/setup-python` instead of the default system Python, so it doesn't have pre-installed old versions of `requests` and `pyopenssl`.  This suggests that we could also resolve the issue by ensuring our workflows use `actions/setup-python`.

**Comment by reaperhulk** [comment] 2022-04-27 19:31
Hey folks, `cryptography` is going to revert our removal of these bindings to allow older versions of pyOpenSSL to upgrade a bit more naturally. The fixes will be in 37.0.1, which we intend to release today.

**Comment by tsibley** [comment] 2022-04-27 19:43
@reaperhulk Ah, excellent! Thanks for letting us know.

**Comment by tsibley** [comment] 2022-04-27 23:39
Resolving this, as I think no further changes are necessary for the CLI. Upstream has put out a new release which resolves this for now (at least until the next major version bump of cryptography) and we've proactively worked around the issue ourselves by improving our GitHub Actions setup in various repos. GitHub Actions is the primary place we ran into this issue because of quirks of the system Python.

**Closed by tsibley** 2022-04-27 23:39 UTC
Labels: bug

**Comment by Alexandredenho** [comment] 2023-09-01 21:45
j'ai besoin d'aide   

Traceback (most recent call last):
  File "D:\Odoo16\odoo\odoo-bin", line 5, in <module>
    import odoo
  File "D:\Odoo16\odoo\odoo\__init__.py", line 113, in <module>
    from . import modules
  File "D:\Odoo16\odoo\odoo\modules\__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry, neutralize
  File "D:\Odoo16\odoo\odoo\modules\graph.py", line 10, in <module>
    import odoo.tools as tools
  File "D:\Odoo16\odoo\odoo\tools\__init__.py", line 22, in <module>
    from .xml_utils import *
  File "D:\Odoo16\odoo\odoo\tools\xml_utils.py", line 5, in <module>
    import requests
  File "D:\Odoo16\venv\lib\site-packages\requests\__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "D:\Odoo16\venv\lib\site-packages\urllib3\contrib\pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "D:\Odoo16\venv\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "D:\Odoo16\venv\lib\site-packages\OpenSSL\crypto.py", line 1556, in <module>
    class X509StoreFlags(object):
  File "D:\Odoo16\venv\lib\site-packages\OpenSSL\crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

**Comment by tsibley** [comment] 2023-09-01 22:12
@Alexandredenho Hi. It looks like you're using an unrelated program, [`oodo-bin`](https://www.odoo.com/documentation/16.0/developer/reference/cli.html), made by the company [Odoo](https://www.odoo.com/). This is not a forum for that program or company. While some of the solutions I noted above may apply given the error message is the same, the noted solutions may do more harm than good in the case of `oodo-bin`, so I can't recommend them. I can't help you with this and suggest you contact Odoo's support team.
