### ISSUE TITLE
Error with bioconda-installed nextstrain.cli when attempting `nextstrain login`

### ISSUE THREAD

**Issue by jgallowa07** [nextstrain/cli#409] opened 2024-12-05 18:49 UTC
### Current Behavior

When installing the nextstrain cli via [bioconda](https://docs.nextstrain.org/projects/cli/en/stable/installation/#from-bioconda) (version 8.5.4), and attempting to `nextstrain login`, I get the following error:

```
raise MissingCryptographyError(
jwt.exceptions.MissingCryptographyError: RS256 requires 'cryptography' to be installed
```

### Expected behavior

`nextstrain login` from bioconda install to work without throwing error shown above.

### How to reproduce
Steps to reproduce the current behavior:
1. `conda create --name nextstrain python=3.11`
2. `conda activate nextstrain`
3. 
```
conda install nextstrain-cli \
  -c conda-forge -c bioconda \
  --strict-channel-priority \
  --override-channels
```
4. Follow `nextstrain login` prompts, pasting the localhost URL into the terminal directly.

### Possible solution

N/A

### Your environment: if browsing Nextstrain online

N/A

### Your environment: if running Nextstrain locally
 - Operating system: 
```
   Static hostname: ermine
         Icon name: computer-server
           Chassis: server
        Machine ID: 082e6f4677ec487b97531d6ccac85d55
           Boot ID: c03d36a071c148e4908b52682691f0f4
  Operating System: Ubuntu 18.04.6 LTS
            Kernel: Linux 4.15.0-189-generic
      Architecture: x86-64
```
 - Browser: chrome
 - Version (e.g. `nextstrain.cli 8.5.4`):

### Additional context

When installing the [linux standalone binary](https://docs.nextstrain.org/projects/cli/en/stable/installation/#standalone) (Also, `nextstrain.cli 8.5.4` in the same compute environment described above),  The `nextstrain login` works as expected.

This was originally pointed out to me by @Caleb-Carr

**Comment by tsibley** [comment] 2024-12-05 19:54
@jgallowa07 I will try to replicate this locally, but I do note that the missing dep, `cryptography`, is [declared in the Bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/3bfb53c3d6dc7da429d2b56a83889e62b29c3156/recipes/nextstrain-cli/meta.yaml#L32). So something unexpected is happening.

Could you share the full traceback of that `MissingCryptographyError`?

**Comment by tsibley** [comment] 2024-12-05 20:19
Thanks. That all looks as expected, i.e. no weirdness with the Python environment itself.

I've reproduced this locally and dug into what's happening. It appears that the `cryptography` dep doesn't make it thru to the final ("rendered") Conda recipe: it's not in [the package](https://api.anaconda.org/download/bioconda/nextstrain-cli/8.5.4/noarch/nextstrain-cli-8.5.4-pyhdfd78af_0.tar.bz2)'s `info/recipe/meta.yaml` (the rendered recipe):

```
  run:
    - boto3
    - docutils
    - fasteners
    - fsspec !=2023.9.1
    - packaging >=3.0.0
    - pyjwt >=2.0.0
    - pyparsing
    - python >=3.8
    - requests
    - s3fs >=2021.04.0,!=2023.9.1
    - typing_extensions >=3.6.4
    - wcmatch >=6.0
    - wrapt
```

nor reported in Anaconda's package metadata API:

```console
$ curl -fsSL https://api.anaconda.org/release/bioconda/nextstrain-cli/8.5.4 | jq '.distributions[0].attrs.depends'
[
  "boto3",
  "docutils",
  "fasteners",
  "fsspec !=2023.9.1",
  "packaging >=3.0.0",
  "pyjwt >=2.0.0",
  "pyparsing",
  "python >=3.8",
  "requests",
  "s3fs >=2021.04.0,!=2023.9.1",
  "typing_extensions >=3.6.4",
  "wcmatch >=6.0",
  "wrapt"
]
```

I think the issue is with the way the dep is declared in the recipe:

```yaml
    - cryptography # Required for pyjwt digital signature support. Replicates "pip install pyjwt[crypto]".
```

I'm guessing that because the comment includes a square-bracketed string (`[crypto]`), it's being treated (erroneously) as a [preprocessing selector](https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#preprocessing-selectors). Someone's regex is too greedy!

I think we can resolve this by moving the comment to its own line instead of a trailing comment.

**Comment by tsibley** [comment] 2024-12-06 08:01
Resolved by https://github.com/bioconda/bioconda-recipes/pull/52618 and release of `nextstrain-cli 8.5.4 pyhdfd78af_1` to Bioconda.

**Closed by tsibley** 2024-12-06 08:01 UTC
Labels: bug

**Comment by jgallowa07** [comment] 2024-12-07 05:35
👏 nice, thank you @tsibley !
